osx_image: xcode6.4

language: objective-c
xcode_project: Travis-CI-Test.xcodeproj # path to your xcodeproj folder
xcode_scheme: Travis-CI-Test

script: xctool -project Travis-CI-Test.xcodeproj -scheme Travis-CI-Test build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO